name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python (you can change version if needed)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: (Optional) Run tests if you have any
      - name: Run tests
        run: |
          if [ -d tests ]; then pytest; else echo "No tests directory found, skipping tests."; fi

      # Step 5: Check app runs (optional sanity check)
      - name: Run app sanity check
        run: |
          python app.py || echo "App run check complete"
